name: hello

on:
  push:
    branches: [main]


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v6

       - name: show branch 
         run: echo "${{ github.ref }}" 

       - name: Show files
         run: ls -la
