name: hello

on:
  push:
    branches: [main]

env:
    APP: demo

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v6

       - name: show branch 
         run: echo "${{ github.ref }}" 

       - name: Show files
         run: ls -la

       - name: show app env
         run: echo "${{ env.APP }}" 

       - name: Run only on main
         if: github.ref == 'refs/heads/main' 
         run: echo "This is main branch"

       - name: Run only when manually triggered
         if: github.event_name == 'workflow_dispatch'
         run: echo "Manual run detected"
