name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Node ci
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v5

     - name: Setup Node
       uses: actions/setup-node@v4
       with:
         node-version: 24
         cache: npm

     - name: Install dependencies
       run: npm ci

     - name: Run test
       run: npm test --if-present
       
     - name: Build
       run: npm run build --if-present

     - name: Upload build output
       if: success()
       uses: actions/upload-artifact@v4
       with:
         name: node-build
         path: |
           dist
           build
       



      
