name: Stage CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Chcekout code
        uses: actions/checkout@v5

      - name: build app
        run: |
          mkdir test
          echo "completed app" > dist/app.txt

      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-build
          path: dist/

  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: verified/
      - run: cat verified/app.txt
          

        

    

    
